#include "nsISupports.idl"

[scriptable, uuid(096f237b-00f7-4046-a02b-388452da5d37)]
interface IProcessManager: nsISupports
{
  readonly attribute unsigned long pid;
  boolean start(in AString filename, in AString curdir);
  boolean stop();
  boolean isRunning();
  void makeTopmost();
  void makeMozWindowTopmost(in AString name); // this doesn't really belong here
  void showTaskBar(in PRBool show); // this doesn't really belong here
  void sendSyntheticKeyEvent(in unsigned long  keycode, in unsigned long scancode, in PRBool alt, in PRBool shift, in PRBool ctrl);
};
