#include "nsISupports.idl"

[scriptable, uuid(1fa69a97-5992-4e63-b481-f77ce86897e4)]
interface ITTS: nsISupports
{
  void speak(in AString what); // uses SAPI XML in text markup see http://msdn.microsoft.com/en-us/library/ms723627(VS.85).aspx
  void stop();
  void alterMasterVolume(in boolean bDec);
};
